if (NOT DEFINED VLC_MINIAUDIO_INPUT OR NOT DEFINED VLC_MINIAUDIO_OUTPUT)
  message(FATAL_ERROR "VLC_MINIAUDIO_INPUT and VLC_MINIAUDIO_OUTPUT are required")
endif ()
file(SHA256 "${VLC_MINIAUDIO_INPUT}" input_hash)
if (NOT input_hash STREQUAL "cc050485bc91a4d4e17a509a898b425be92825174bffd56b1576a5bcf15dcd3d")
  message(FATAL_ERROR "Published miniaudio header changed; review the VLC WASAPI extension before building")
endif ()
file(READ "${VLC_MINIAUDIO_INPUT}" source)
string(REPLACE "\r\n" "\n" source "${source}")

function(vlc_patch before after)
  string(FIND "${source}" "${before}" first)
  if (first EQUAL -1)
    message(FATAL_ERROR "VLC WASAPI patch anchor missing: ${before}")
  endif ()
  string(LENGTH "${before}" length)
  math(EXPR end "${first} + ${length}")
  string(SUBSTRING "${source}" ${end} -1 remainder)
  string(FIND "${remainder}" "${before}" duplicate)
  if (NOT duplicate EQUAL -1)
    message(FATAL_ERROR "VLC WASAPI patch anchor is not unique: ${before}")
  endif ()
  string(REPLACE "${before}" "${after}" source "${source}")
  set(source "${source}" PARENT_SCOPE)
endfunction()

set(anchor "static ma_result ma_device_data_loop__wasapi(ma_device* pDevice)\n{")
vlc_patch("${anchor}" "#include \"llvlcwasapi.h\"\n\n${anchor}\n    if (pDevice->type == ma_device_type_playback) return llvlc_wasapi_loop(pDevice);")

set(anchor "static HRESULT STDMETHODCALLTYPE ma_IMMNotificationClient_OnDeviceStateChanged(ma_IMMNotificationClient* pThis, LPCWSTR pDeviceID, DWORD dwNewState)\n{")
vlc_patch("${anchor}" "${anchor}\n    if (pThis->pDevice->type == ma_device_type_playback) {\n        if (pDeviceID && wcscmp(pDeviceID, pThis->pDevice->playback.id.wasapi) == 0 && !(dwNewState & MA_MM_DEVICE_STATE_ACTIVE))\n            llvlc::WasapiEndpoint::invalidate(pThis->pDevice);\n        return S_OK;\n    }")

set(anchor "static HRESULT STDMETHODCALLTYPE ma_IMMNotificationClient_OnDeviceRemoved(ma_IMMNotificationClient* pThis, LPCWSTR pDeviceID)\n{")
vlc_patch("${anchor}" "${anchor}\n    if (pThis->pDevice->type == ma_device_type_playback) {\n        if (pDeviceID && wcscmp(pDeviceID, pThis->pDevice->playback.id.wasapi) == 0)\n            llvlc::WasapiEndpoint::invalidate(pThis->pDevice);\n        return S_OK;\n    }")

set(anchor "static HRESULT STDMETHODCALLTYPE ma_IMMNotificationClient_OnDefaultDeviceChanged(ma_IMMNotificationClient* pThis, ma_EDataFlow dataFlow, ma_ERole role, LPCWSTR pDefaultDeviceID)\n{")
vlc_patch("${anchor}" "${anchor}\n    if (pThis->pDevice->type == ma_device_type_playback) {\n        if (dataFlow == ma_eRender && role == ma_eConsole && (!pDefaultDeviceID || wcscmp(pDefaultDeviceID, pThis->pDevice->playback.id.wasapi) != 0))\n            llvlc::WasapiEndpoint::invalidate(pThis->pDevice);\n        return S_OK;\n    }")

get_filename_component(output_directory "${VLC_MINIAUDIO_OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
set(previous "")
if (EXISTS "${VLC_MINIAUDIO_OUTPUT}")
  file(READ "${VLC_MINIAUDIO_OUTPUT}" previous)
endif ()
if (NOT previous STREQUAL source)
  file(WRITE "${VLC_MINIAUDIO_OUTPUT}" "${source}")
endif ()