VLC_SYM( libvlc_audio_set_volume, int, libvlc_media_player_t *, int  )
VLC_SYM( libvlc_event_attach, int, libvlc_event_manager_t *, libvlc_event_type_t, libvlc_callback_t, void * )
VLC_SYM( libvlc_event_detach, void, libvlc_event_manager_t *, libvlc_event_type_t, libvlc_callback_t, void * )
VLC_SYM( libvlc_media_add_option, void, libvlc_media_t *, const char * )
VLC_SYM( libvlc_media_get_duration, libvlc_time_t, libvlc_media_t* )
VLC_SYM( libvlc_media_get_meta, char*, libvlc_media_t *, libvlc_meta_t )
VLC_SYM( libvlc_media_new_location, libvlc_media_t*, libvlc_instance_t *, const char * )
VLC_SYM( libvlc_media_player_event_manager, libvlc_event_manager_t*, libvlc_media_player_t* )
VLC_SYM( libvlc_media_player_get_time, libvlc_time_t, libvlc_media_player_t* )
VLC_SYM( libvlc_media_player_new_from_media, libvlc_media_player_t*, libvlc_media_t* )
VLC_SYM( libvlc_media_player_pause, void, libvlc_media_player_t* )
VLC_SYM( libvlc_media_player_play, int, libvlc_media_player_t* )
VLC_SYM( libvlc_media_player_release, void, libvlc_media_player_t* )
VLC_SYM( libvlc_media_player_set_position, void, libvlc_media_player_t*, float )
VLC_SYM( libvlc_media_player_stop, void, libvlc_media_player_t* )
VLC_SYM( libvlc_media_release, void, libvlc_media_t* )
VLC_SYM( libvlc_new, libvlc_instance_t*, int, const char *const * )
VLC_SYM( libvlc_release, void, libvlc_instance_t* )
VLC_SYM( libvlc_video_set_callbacks, void, libvlc_media_player_t *, libvlc_video_lock_cb, libvlc_video_unlock_cb, libvlc_video_display_cb, void * )
VLC_SYM( libvlc_video_set_format, void, libvlc_media_player_t *, const char *, unsigned, unsigned height, unsigned )
