SET LL_BUILD_WINDOWS_BASE_MACROS=/D_SECURE_STL=0 /D_HAS_ITERATOR_DEBUGGING=0 /DWIN32 /D_WINDOWS /DLL_WINDOWS=1 /DUNICODE /D_UNICODE /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 /DLL_OS_DRAGDROP_ENABLED=1 /DLIB_NDOF=1
SET LL_BUILD_WINDOWS_BASE_SWITCHES=/std:c++17 /Zc:wchar_t- /Zi /GR /DEBUG
SET LL_BUILD_WINDOWS_BASE=%LL_BUILD_WINDOWS_BASE_SWITCHES% %LL_BUILD_WINDOWS_BASE_MACROS%

SET LL_BUILD_WINDOWS_RELEASE_MACROS=/DLL_RELEASE=1 /DLL_RELEASE_FOR_DOWNLOAD=1 /DNDEBUG %LL_BUILD_WINDOWS_BASE_MACROS%
SET LL_BUILD_WINDOWS_RELEASE_SWITCHES=/MD /O2 /Ob2 %LL_BUILD_WINDOWS_BASE_SWITCHES%
SET LL_BUILD_WINDOWS_RELEASE=%LL_BUILD_WINDOWS_RELEASE_SWITCHES% %LL_BUILD_WINDOWS_RELEASE_MACROS%
SET LL_BUILD_WINDOWS_RELEASEOS=%LL_BUILD_WINDOWS_RELEASE%
SET LL_BUILD_WINDOWS_RELEASEFS=%LL_BUILD_WINDOWS_RELEASE%
SET LL_BUILD_WINDOWS_RELEASEFS_AVX=LL_BUILD_WINDOWS_RELEASE
SET LL_BUILD_WINDOWS_RELEASEFS_AVX2=LL_BUILD_WINDOWS_RELEASE
SET LL_BUILD_WINDOWS_RELEASEFS_OPEN=LL_BUILD_WINDOWS_RELEASE

SET LL_BUILD_WINDOWS_RELWITHDEBINFO_MACROS=/DLL_RELEASE=1 /DLL_RELEASE_WITH_DEBUG_INFO=1 /DNDEBUG %LL_BUILD_WINDOWS_BASE_MACROS%
SET LL_BUILD_WINDOWS_RELWITHDEBINFO_SWITCHES=/MD /Od /Ob0 %LL_BUILD_WINDOWS_BASE_SWITCHES%
SET LL_BUILD_WINDOWS_RELWITHDEBINFO=%LL_BUILD_WINDOWS_RELWITHDEBINFO_SWITCHES% %LL_BUILD_WINDOWS_RELWITHDEBINFO_MACROS%
SET LL_BUILD_WINDOWS_RELWITHDEBINFOOS=%LL_BUILD_WINDOWS_RELWITHDEBINFO%
SET LL_BUILD_WINDOWS_RELWITHDEBINFOFS=%LL_BUILD_WINDOWS_RELWITHDEBINFO%
SET LL_BUILD_WINDOWS_RELWITHDEBINFOFS_OPEN=%LL_BUILD_WINDOWS_RELWITHDEBINFO%

SET LL_BUILD_WINDOWS_DEBUG_MACROS=/D_DEBUG /DLL_DEBUG=1 /D_SCL_SECURE_NO_WARNINGS=1 %LL_BUILD_WINDOWS_BASE_MACROS%
SET LL_BUILD_WINDOWS_DEBUG_SWITCHES=/MDd /Od /NODEFAULTLIB:LIBCMTD /NODEFAULTLIB:MSVCRT %LL_BUILD_WINDOWS_BASE_SWITCHES%
SET LL_BUILD_WINDOWS_DEBUG=%LL_BUILD_WINDOWS_DEBUG_SWITCHES% %LL_BUILD_WINDOWS_DEBUG_MACROS%
SET LL_BUILD_WINDOWS_DEBUGOS=%LL_BUILD_WINDOWS_DEBUG%

SET LL_BUILD=%LL_BUILD_WINDOWS_RELEASE%

SET AUTOBUILD_VARIABLES_FILE=E:\dev\Firestorm\fs-build-variables\variables
SET AUTOBUILD_VSVER=170
SET AUTOBUILD_CONFIG_FILE=my_autobuild.xml
