; Vulkanstorm viewer installer (Inno Setup 7)
; Replaces the legacy NSIS installer for the VulkanStorm build.
;
; This library is free software; you can redistribute it and/or
; modify it under the terms of the GNU Lesser General Public
; License as published by the Free Software Foundation;
; version 2.1 of the License only.
;
; This script is preprocessed by viewer_manifest.py before ISCC is invoked.
; Tokens of the form %%NAME%% are substituted by the manifest.
;
; Ported from the archived VulkanStorm Inno script: it ships an explicit file
; list (%%INSTALL_FILES%%) generated from the packaged file_list, so only the
; intended files are installed (never the intermediate vulkanstorm-bin.exe,
; stray build-type variants, symbol files, or the installer itself).

#define AppName        "%%APP_NAME%%"
#define AppNameOneWord "%%APP_NAME_ONEWORD%%"
#define FriendlyAppName "%%FRIENDLY_APP_NAME%%"
#define AppVersion     "%%VERSION%%"
#define ViewerExe      "%%FINAL_EXE%%"
#define IsOpenSim      %%IS_OPENSIM%%
#define InstallerFile  "%%INSTALLER_FILE%%"
#define InstallerOut   "%%INSTALLER_OUT%%"
#define SourceDir      "%%SOURCE_DIR%%"
#define LicenseFile    "%%LICENSE_FILE%%"
#define SetupIcon      "%%SETUP_ICON%%"
#define AppURL         "%%DL_URL%%"

[Setup]
; Stable per-product upgrade GUID. Keep this constant so upgrades/reinstalls
; detect and upgrade prior installs instead of side-by-side installing.
AppId={{7A4C2E91-3F5B-4D6A-9C1E-5E8F2A6B9D04}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=The Vulkanstorm Project
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
; Install into 64-bit Program Files: {autopf64} always resolves to the x64
; Program Files (never Program Files (x86)).
DefaultDirName={autopf64}\{#AppNameOneWord}
DefaultGroupName={#AppName}
; Keep the wizard pages (incl. the tasks/ready/finish pages) visible so the
; optional choices below are presented.
DisableProgramGroupPage=auto
; Require 64-bit Windows and install in 64-bit mode.
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=6.1sp1
; Show the LGPL-2.1 license agreement before anything else.
LicenseFile={#LicenseFile}
; OutputBaseFilename must NOT carry .exe (ISCC appends it). The manifest
; passes InstallerOut = <base>_Setup so the result is <base>_Setup.exe.
OutputBaseFilename={#InstallerOut}
OutputDir={#SourceDir}
SetupIconFile={#SetupIcon}
UninstallDisplayIcon={app}\{#ViewerExe}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
CloseApplications=yes
CloseApplicationsFilter={#ViewerExe}
RestartApplications=no
ChangesAssociations=yes
VersionInfoVersion={#AppVersion}
VersionInfoCompany=The Vulkanstorm Project
VersionInfoDescription={#AppName} installer
VersionInfoProductName={#AppName}
VersionInfoProductVersion={#AppVersion}
; Register an uninstaller entry.
Uninstallable=yes
CreateUninstallRegKey=yes

[Languages]
Name: "en"; MessagesFile: "compiler:Default.isl"

[Tasks]
; checkedonce: offered, ticked by default on first install only.
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional actions:"; Flags: checkedonce
Name: "protocols"; Description: "Register {#AppName} for secondlife://, hypergrid and hop:// links"; GroupDescription: "Additional actions:"; Flags: checkedonce

[Files]
; Explicit per-file list generated by the manifest (viewer_manifest.py's
; inno_file_commands). This is what keeps dev artifacts and stray executables
; out of the installation.
%%INSTALL_FILES%%

[InstallDelete]
; Clean the previous install dir on upgrade so removed/renamed files don't linger.
Type: filesandordirs; Name: "{app}\*"

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#ViewerExe}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#ViewerExe}"; Tasks: desktopicon

[Run]
; "Launch Vulkanstorm" checkbox on the successful-completion page.
Filename: "{app}\{#ViewerExe}"; Description: "Launch {#AppName} now"; Flags: nowait postinstall skipifsilent unchecked

[Registry]
; Product registration (always).
Root: HKLM; Subkey: "SOFTWARE\The Vulkanstorm Project\{#AppNameOneWord}"; ValueType: string; ValueName: ""; ValueData: "{app}"; Flags: uninsdeletekey
Root: HKLM; Subkey: "SOFTWARE\The Vulkanstorm Project\{#AppNameOneWord}"; ValueType: string; ValueName: "Version"; ValueData: "{#AppVersion}"
Root: HKLM; Subkey: "SOFTWARE\The Vulkanstorm Project\{#AppNameOneWord}"; ValueType: string; ValueName: "Shortcut"; ValueData: "{#AppName}"
Root: HKLM; Subkey: "SOFTWARE\The Vulkanstorm Project\{#AppNameOneWord}"; ValueType: string; ValueName: "Exe"; ValueData: "{#ViewerExe}"
; URL protocol handlers (secondlife://, hypergrid, hop://), only when the user
; opted in via the "protocols" task. The URL parameter is passed last; the
; viewer ignores subsequent params (MAIT-8305 semantics preserved).
Root: HKCR; Subkey: "secondlife"; ValueType: string; ValueName: ""; ValueData: "URL:Second Life"; Tasks: protocols; Flags: uninsdeletekey
Root: HKCR; Subkey: "secondlife"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Tasks: protocols
Root: HKCR; Subkey: "secondlife\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\{#ViewerExe}"""; Tasks: protocols
Root: HKCR; Subkey: "secondlife\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "{#FriendlyAppName}"; Tasks: protocols
Root: HKCR; Subkey: "secondlife\shell\open\command"; ValueType: expandsz; ValueName: ""; ValueData: """{app}\{#ViewerExe}"" -url ""%1"""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-location-info"; ValueType: string; ValueName: ""; ValueData: "URL:Hypergrid"; Tasks: protocols; Flags: uninsdeletekey
Root: HKCR; Subkey: "x-grid-location-info"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-location-info\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\{#ViewerExe}"""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-location-info\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "{#FriendlyAppName}"; Tasks: protocols
Root: HKCR; Subkey: "x-grid-location-info\shell\open\command"; ValueType: expandsz; ValueName: ""; ValueData: """{app}\{#ViewerExe}"" -url ""%1"""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-info"; ValueType: string; ValueName: ""; ValueData: "URL:Hypergrid"; Tasks: protocols; Flags: uninsdeletekey
Root: HKCR; Subkey: "x-grid-info"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-info\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\{#ViewerExe}"""; Tasks: protocols
Root: HKCR; Subkey: "x-grid-info\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "{#FriendlyAppName}"; Tasks: protocols
Root: HKCR; Subkey: "x-grid-info\shell\open\command"; ValueType: expandsz; ValueName: ""; ValueData: """{app}\{#ViewerExe}"" -url ""%1"""; Tasks: protocols
; hop:// is registered only for OpenSim builds (IsOpenSimBuild reads the
; {#IsOpenSim} define the manifest zeroes for Second Life builds).
Root: HKCR; Subkey: "hop"; ValueType: string; ValueName: ""; ValueData: "URL:Hypergrid"; Tasks: protocols; Check: IsOpenSimBuild; Flags: uninsdeletekey
Root: HKCR; Subkey: "hop"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""; Tasks: protocols; Check: IsOpenSimBuild
Root: HKCR; Subkey: "hop\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: """{app}\{#ViewerExe}"""; Tasks: protocols; Check: IsOpenSimBuild
Root: HKCR; Subkey: "hop\shell\open"; ValueType: string; ValueName: "FriendlyAppName"; ValueData: "{#FriendlyAppName}"; Tasks: protocols; Check: IsOpenSimBuild
Root: HKCR; Subkey: "hop\shell\open\command"; ValueType: expandsz; ValueName: ""; ValueData: """{app}\{#ViewerExe}"" -url ""%1"""; Tasks: protocols; Check: IsOpenSimBuild

[Code]
function IsOpenSimBuild: Boolean;
begin
  Result := ({#IsOpenSim} <> 0);
end;