cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED TEST_BINARY_DIR)
    message(FATAL_ERROR "Pass a worktree-owned TEST_BINARY_DIR")
endif()
get_filename_component(audio_modules "${CMAKE_CURRENT_LIST_DIR}/../../cmake" ABSOLUTE)
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/source/stubs")
file(WRITE "${TEST_BINARY_DIR}/source/stubs/Linking.cmake" "")
file(WRITE "${TEST_BINARY_DIR}/source/stubs/Prebuilt.cmake" [=[
macro(use_prebuilt_binary package)
    list(APPEND requested_packages "${package}")
endmacro()
]=])
file(WRITE "${TEST_BINARY_DIR}/source/CMakeLists.txt" "cmake_minimum_required(VERSION 3.24)\nproject(AudioSelection NONE)\nlist(APPEND CMAKE_MODULE_PATH \"\${CMAKE_CURRENT_SOURCE_DIR}/stubs\" \"${audio_modules}\")\n")
file(APPEND "${TEST_BINARY_DIR}/source/CMakeLists.txt" [=[
if(NOT DEFINED WINDOWS)
    set(WINDOWS ON)
endif()
if(NOT DEFINED ADDRESS_SIZE)
    set(ADDRESS_SIZE 64)
endif()
set(LIBS_PREBUILT_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
set(SOLOUD_LIBRARY "${CMAKE_CURRENT_LIST_FILE}")
set(FMOD_LIBRARY "${CMAKE_CURRENT_LIST_FILE}")
set(OPENAL_LIBRARY "${CMAKE_CURRENT_LIST_FILE}")
set(ALUT_LIBRARY "${CMAKE_CURRENT_LIST_FILE}")
include(FMODSTUDIO)
include(OPENAL)
include(SOLOUD)
set(actual_targets)
foreach(backend soloud openal fmodstudio)
    if(TARGET ll::${backend})
        list(APPEND actual_targets "${backend}")
    endif()
endforeach()
if(NOT "${actual_targets}" STREQUAL "${EXPECT_BACKEND}")
    message(FATAL_ERROR "Expected ${EXPECT_BACKEND}, got ${actual_targets}")
endif()
if(NOT "${requested_packages}" STREQUAL "${EXPECT_BACKEND}")
    message(FATAL_ERROR "Unexpected packages: ${requested_packages}")
endif()
]=])

function(check_selection name backend)
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/source"
        -B "${TEST_BINARY_DIR}/${name}" "-DEXPECT_BACKEND=${backend}" ${ARGN}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${name}: ${output}\n${errors}")
    endif()
    message(STATUS "PASS: ${name} -> ${backend}")
endfunction()

check_selection(default soloud)
check_selection(proprietary soloud -DINSTALL_PROPRIETARY=ON)
check_selection(openal openal -DUSE_OPENAL=ON)
check_selection(fmod fmodstudio -DUSE_FMODSTUDIO=ON)
check_selection(legacy_openal openal -DOPENAL=ON)
check_selection(legacy_fmod fmodstudio -DFMODSTUDIO=ON)
check_selection(reconfigure openal -DUSE_SOLOUD=OFF -DUSE_OPENAL=ON -DUSE_FMODSTUDIO=OFF)
check_selection(reconfigure fmodstudio -DUSE_SOLOUD=OFF -DUSE_OPENAL=OFF -DUSE_FMODSTUDIO=ON)
check_selection(reconfigure soloud -DUSE_SOLOUD=ON -DUSE_OPENAL=OFF -DUSE_FMODSTUDIO=OFF -DOPENAL=OFF -DFMODSTUDIO=OFF)
check_selection(unsupported_optional openal -DWINDOWS=OFF -DUSE_SOLOUD=OFF -DUSE_OPENAL=ON)

foreach(failure conflict platform architecture)
    set(flags -DUSE_SOLOUD=ON)
    if(failure STREQUAL conflict)
        list(APPEND flags -DUSE_OPENAL=ON)
        set(expected "Select one audio backend")
    elseif(failure STREQUAL platform)
        list(APPEND flags -DWINDOWS=OFF)
        set(expected "Windows x64 only")
    else()
        list(APPEND flags -DADDRESS_SIZE=32)
        set(expected "Windows x64 only")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${TEST_BINARY_DIR}/source"
        -B "${TEST_BINARY_DIR}/${failure}" ${flags}
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(status EQUAL 0 OR NOT "${errors}" MATCHES "${expected}")
        message(FATAL_ERROR "${failure}: missing expected diagnostic: ${output}\n${errors}")
    endif()
    message(STATUS "PASS: ${failure} rejected explicitly")
endforeach()