/*
 * @file fsfloatercontactsetconfiguration.cpp
 * @brief Contact set configuration floater
 *
 * (C) 2013 Cinder Roxley @ Second Life <cinder.roxley@phoenixviewer.com>
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include "llviewerprecompiledheaders.h"

#include "fsfloatercontactsetconfiguration.h"

#include "lggcontactsets.h"
#include "llbutton.h"
#include "llcheckboxctrl.h"
#include "llcolorswatch.h"
#include "lllineeditor.h"
#include "llnotificationsutil.h"
#include "lltexteditor.h"
#include "llviewercontrol.h"

FSFloaterContactSetConfiguration::FSFloaterContactSetConfiguration(const LLSD& target_set)
:   LLFloater(target_set),
    mContextConeOpacity(0.f),
    mContextConeInAlpha(CONTEXT_CONE_IN_ALPHA),
    mContextConeOutAlpha(CONTEXT_CONE_OUT_ALPHA),
    mContextConeFadeTime(CONTEXT_CONE_FADE_TIME)
{
    mContactSet = target_set.asString();
}

bool FSFloaterContactSetConfiguration::postBuild()
{
    updateTitle();

    mSetName = getChild<LLLineEditor>("set_name_editor");
    mSetName->setText(mContactSet);

    mRenameButton = getChild<LLButton>("rename_btn");
    mRenameButton->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onRenameSet, this));

    mSetSwatch = getChild<LLColorSwatchCtrl>("set_swatch");
    mSetSwatch->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetColor, this));

    mGlobalSwatch = getChild<LLColorSwatchCtrl>("global_swatch");
    mGlobalSwatch->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitDefaultColor, this));

    mNotificationCheckBox = getChild<LLCheckBoxCtrl>("show_set_notifications");
    mNotificationCheckBox->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetNotifications, this));

    mSortByOnlineStatusCheckBox = getChild<LLCheckBoxCtrl>("sort_by_online_status");
    mSortByOnlineStatusCheckBox->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetSortByOnlineStatus, this));

    mAutoresponseBusyEnabledCheckBox = getChild<LLCheckBoxCtrl>("set_autoresponse_busy_enabled");
    mAutoresponseBusyEnabledCheckBox->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseBusy, this));
    mAutoresponseBusyEditor = getChild<LLTextEditor>("set_autoresponse_busy");
    mAutoresponseBusyEditor->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseBusy, this));

    mAutoresponseModeEnabledCheckBox = getChild<LLCheckBoxCtrl>("set_autoresponse_mode_enabled");
    mAutoresponseModeEnabledCheckBox->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseMode, this));
    mAutoresponseModeEditor = getChild<LLTextEditor>("set_autoresponse_mode");
    mAutoresponseModeEditor->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseMode, this));

    mAutoresponseNonFriendsEnabledCheckBox = getChild<LLCheckBoxCtrl>("set_autoresponse_nonfriends_enabled");
    mAutoresponseNonFriendsEnabledCheckBox->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseNonFriends, this));
    mAutoresponseNonFriendsEditor = getChild<LLTextEditor>("set_autoresponse_nonfriends");
    mAutoresponseNonFriendsEditor->setCommitCallback(boost::bind(&FSFloaterContactSetConfiguration::onCommitSetAutoresponseNonFriends, this));
    return true;
}

void FSFloaterContactSetConfiguration::draw()
{
    static LLCachedControl<F32> max_opacity(gSavedSettings, "PickerContextOpacity", 0.4f);
    drawConeToOwner(mContextConeOpacity, max_opacity, mFrustumOrigin.get(), mContextConeFadeTime, mContextConeInAlpha, mContextConeOutAlpha);
    LLFloater::draw();
}

void FSFloaterContactSetConfiguration::onOpen(const LLSD& target_set)
{
    bool enabled = false;
    std::string response;

    mSetSwatch->set(LGGContactSets::getInstance()->getSetColor(mContactSet), true);
    mGlobalSwatch->set(LGGContactSets::getInstance()->getDefaultColor(), true);
    mNotificationCheckBox->set(LGGContactSets::getInstance()->getNotifyForSet(mContactSet));
    mSortByOnlineStatusCheckBox->set(LGGContactSets::getInstance()->getSortByOnlineStatusForSet(mContactSet));

    LGGContactSets::getInstance()->getAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::BUSY, enabled, response);
    mAutoresponseBusyEnabledCheckBox->set(enabled);
    mAutoresponseBusyEditor->setText(response);

    LGGContactSets::getInstance()->getAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::AUTORESPONSE, enabled, response);
    mAutoresponseModeEnabledCheckBox->set(enabled);
    mAutoresponseModeEditor->setText(response);

    LGGContactSets::getInstance()->getAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::AUTORESPONSE_NONFRIENDS, enabled, response);
    mAutoresponseNonFriendsEnabledCheckBox->set(enabled);
    mAutoresponseNonFriendsEditor->setText(response);
    updateAutoresponseEditorEnabledState();
}

void FSFloaterContactSetConfiguration::onCommitSetColor()
{
    LGGContactSets::getInstance()->setSetColor(mContactSet, mSetSwatch->get());
}

void FSFloaterContactSetConfiguration::onCommitSetNotifications()
{
    LGGContactSets::getInstance()->setNotifyForSet(mContactSet, mNotificationCheckBox->getValue().asBoolean());
}

void FSFloaterContactSetConfiguration::onCommitSetSortByOnlineStatus()
{
    LGGContactSets::getInstance()->setSortByOnlineStatusForSet(mContactSet, mSortByOnlineStatusCheckBox->getValue().asBoolean());
}

void FSFloaterContactSetConfiguration::onCommitDefaultColor()
{
    LGGContactSets::getInstance()->setDefaultColor(mGlobalSwatch->get());
}

void FSFloaterContactSetConfiguration::onCommitSetAutoresponseBusy()
{
    LGGContactSets::getInstance()->setAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::BUSY, mAutoresponseBusyEnabledCheckBox->getValue().asBoolean(), mAutoresponseBusyEditor->getText());
    updateAutoresponseEditorEnabledState();
}

void FSFloaterContactSetConfiguration::onCommitSetAutoresponseMode()
{
    LGGContactSets::getInstance()->setAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::AUTORESPONSE, mAutoresponseModeEnabledCheckBox->getValue().asBoolean(), mAutoresponseModeEditor->getText());
    updateAutoresponseEditorEnabledState();
}

void FSFloaterContactSetConfiguration::onCommitSetAutoresponseNonFriends()
{
    LGGContactSets::getInstance()->setAutoresponseForSet(mContactSet, ContactSetAutoresponseMode::AUTORESPONSE_NONFRIENDS, mAutoresponseNonFriendsEnabledCheckBox->getValue().asBoolean(), mAutoresponseNonFriendsEditor->getText());
    updateAutoresponseEditorEnabledState();
}

void FSFloaterContactSetConfiguration::onRenameSet()
{
    std::string new_name = mSetName->getText();

    if (!new_name.empty() && LGGContactSets::getInstance()->renameSet(mContactSet, new_name))
    {
        mKey = LLSD(new_name);
        mContactSet = new_name;
        updateTitle();
    }
    else
    {
        LLSD substitutions;
        substitutions["SET"] = mContactSet;
        substitutions["NEW_NAME"] = new_name;
        LLNotificationsUtil::add("RenameContactSetFailure", substitutions);
    }
}

void FSFloaterContactSetConfiguration::updateTitle()
{
    LLStringUtil::format_map_t map;
    map["NAME"] = mContactSet;
    setTitle(getString("title", map));
}

void FSFloaterContactSetConfiguration::setFrustumOrigin(LLView* frustumOrigin)
{
    if (frustumOrigin)
    {
        mFrustumOrigin = frustumOrigin->getHandle();
    }
}

void FSFloaterContactSetConfiguration::updateAutoresponseEditorEnabledState()
{
    mAutoresponseBusyEditor->setEnabled(mAutoresponseBusyEnabledCheckBox->getValue().asBoolean());
    mAutoresponseModeEditor->setEnabled(mAutoresponseModeEnabledCheckBox->getValue().asBoolean());
    mAutoresponseNonFriendsEditor->setEnabled(mAutoresponseNonFriendsEnabledCheckBox->getValue().asBoolean());
}
