/** 
 * @file kvflickr.h
 * @brief Basic Flickr library for the client.
 * @copyright Copyright (c) 2011 Katharine Berry
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#ifndef KV_KVFLICKR_H
#define KV_KVFLICKR_H

#include "llimage.h"
#include "llsd.h"

#include <boost/bind.hpp>

// This include file defines the API key/secret.
// It is generated by cmake.
#include "kvflickrkeys.h"

class KVFlickrRequest
{
public:
	typedef boost::function<void(bool success, const LLSD& response)> response_callback_t;
	
	static void request(const std::string& method, const LLSD& args, response_callback_t callback);
	static void uploadPhoto(const LLSD& args, LLImageFormatted *image, response_callback_t callback);
	static std::string getSignatureForCall(const LLSD& parameters, bool encoded);
};

#endif
