name: Build Firestorm Linux

on:
  workflow_dispatch: # 手動実行

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake python3 python3-pip \
            build-essential g++ \
            libgl1-mesa-dev libglu1-mesa-dev \
            libgtk-3-dev libpulse-dev \
            libxinerama-dev libxrandr-dev libxi-dev \
            libxext-dev libx11-dev \
            libdbus-1-dev libssl-dev \
            libcurl4-openssl-dev libpng-dev \
            libopenal-dev libvorbis-dev libopus-dev \
            libxml2-dev

      - name: Install autobuild
        run: pip3 install --upgrade autobuild

      - name: Configure Firestorm
        run: autobuild configure -c ReleaseFS_open

      - name: Build Firestorm
        run: autobuild build -c ReleaseFS_open --no-configure

      - name: Package Firestorm
        run: autobuild package -c ReleaseFS_open

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-linux
          path: build-linux-newview/packaged
