name: Build viewer

on:
  workflow_dispatch:
  push:
    branches: ["Firestorm*.*.*", "*alpha", "*nightly", "*preview"]
  schedule:
    - cron: '00 03 * * *'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/build.yaml
